'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Concours

 '''<summary>
 '''cmdAddDistance control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents cmdAddDistance As Global.System.Web.UI.WebControls.LinkButton

 '''<summary>
 '''tabMyFlights control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents tabMyFlights As Global.System.Web.UI.HtmlControls.HtmlGenericControl

 '''<summary>
 '''tabUnvalidatedFlights control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents tabUnvalidatedFlights As Global.System.Web.UI.HtmlControls.HtmlGenericControl
End Class
