'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class DistanceEdit
    
    '''<summary>
    '''lblFlightDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblFlightDate As Global.System.Web.UI.UserControl
    
    '''<summary>
    '''dpFlightDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dpFlightDate As Global.DotNetNuke.Web.UI.WebControls.DnnDatePicker
    
    '''<summary>
    '''reqFlightDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents reqFlightDate As Global.System.Web.UI.WebControls.RequiredFieldValidator
    
    '''<summary>
    '''lblCategory control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCategory As Global.System.Web.UI.UserControl
    
    '''<summary>
    '''ddCategory control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddCategory As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''lblFlightType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblFlightType As Global.System.Web.UI.UserControl
    
    '''<summary>
    '''ddFlightType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddFlightType As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''lblComments control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblComments As Global.System.Web.UI.UserControl
    
    '''<summary>
    '''txtComments control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtComments As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''trSummary control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents trSummary As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''lblSummary control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSummary As Global.System.Web.UI.UserControl
    
    '''<summary>
    '''txtSummary control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSummary As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''trTotalDistance control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents trTotalDistance As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''lblTotalDistance control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTotalDistance As Global.System.Web.UI.UserControl
    
    '''<summary>
    '''txtTotalDistance control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTotalDistance As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''regTotalDistance control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents regTotalDistance As Global.System.Web.UI.WebControls.RegularExpressionValidator
    
    '''<summary>
    '''cmdRecalculate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdRecalculate As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''trTotalPoints control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents trTotalPoints As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''lblTotalPoints control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTotalPoints As Global.System.Web.UI.UserControl
    
    '''<summary>
    '''txtTotalPoints control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTotalPoints As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''regTotalPoints control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents regTotalPoints As Global.System.Web.UI.WebControls.RegularExpressionValidator
    
    '''<summary>
    '''txtDescriptionStart control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDescriptionStart As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''reqDescriptionStart control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents reqDescriptionStart As Global.System.Web.UI.WebControls.RequiredFieldValidator
    
    '''<summary>
    '''tpTimeStart control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tpTimeStart As Global.DotNetNuke.Web.UI.WebControls.DnnTimePicker
    
    '''<summary>
    '''reqTimeStart control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents reqTimeStart As Global.System.Web.UI.WebControls.RequiredFieldValidator
    
    '''<summary>
    '''txtCoordinatesStart control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCoordinatesStart As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''reqCoordinatesStart control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents reqCoordinatesStart As Global.System.Web.UI.WebControls.RequiredFieldValidator
    
    '''<summary>
    '''regCoordinatesStart control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents regCoordinatesStart As Global.System.Web.UI.WebControls.RegularExpressionValidator
    
    '''<summary>
    '''lblA control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblA As Global.System.Web.UI.UserControl
    
    '''<summary>
    '''txtDescriptionA control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDescriptionA As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''tpTimeA control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tpTimeA As Global.DotNetNuke.Web.UI.WebControls.DnnTimePicker
    
    '''<summary>
    '''txtCoordinatesA control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCoordinatesA As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''regCoordinatesA control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents regCoordinatesA As Global.System.Web.UI.WebControls.RegularExpressionValidator
    
    '''<summary>
    '''lblC1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblC1 As Global.System.Web.UI.UserControl
    
    '''<summary>
    '''txtDescriptionC1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDescriptionC1 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtCoordinatesC1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCoordinatesC1 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''regCoordinatesC1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents regCoordinatesC1 As Global.System.Web.UI.WebControls.RegularExpressionValidator
    
    '''<summary>
    '''lblC2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblC2 As Global.System.Web.UI.UserControl
    
    '''<summary>
    '''txtDescriptionC2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDescriptionC2 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtCoordinatesC2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCoordinatesC2 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''regCoordinatesC2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents regCoordinatesC2 As Global.System.Web.UI.WebControls.RegularExpressionValidator
    
    '''<summary>
    '''lblB control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblB As Global.System.Web.UI.UserControl
    
    '''<summary>
    '''txtDescriptionB control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDescriptionB As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''tpTimeB control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tpTimeB As Global.DotNetNuke.Web.UI.WebControls.DnnTimePicker
    
    '''<summary>
    '''txtCoordinatesB control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCoordinatesB As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''regCoordinatesB control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents regCoordinatesB As Global.System.Web.UI.WebControls.RegularExpressionValidator
    
    '''<summary>
    '''txtDescriptionLanding control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDescriptionLanding As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''tpTimeLanding control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tpTimeLanding As Global.DotNetNuke.Web.UI.WebControls.DnnTimePicker
    
    '''<summary>
    '''reqTimeLanding control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents reqTimeLanding As Global.System.Web.UI.WebControls.RequiredFieldValidator
    
    '''<summary>
    '''txtCoordinatesLanding control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCoordinatesLanding As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''reqCoordinatesLanding control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents reqCoordinatesLanding As Global.System.Web.UI.WebControls.RequiredFieldValidator
    
    '''<summary>
    '''regCoordinatesLanding control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents regCoordinatesLanding As Global.System.Web.UI.WebControls.RegularExpressionValidator
    
    '''<summary>
    '''msgBoxError control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents msgBoxError As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''msgError control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents msgError As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''cmdCancel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdCancel As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''cmdSubmit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdSubmit As Global.System.Web.UI.WebControls.LinkButton
End Class
