'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class DistanceView

 '''<summary>
 '''lblPilot control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents lblPilot As Global.System.Web.UI.UserControl

 '''<summary>
 '''lblFlightDate control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents lblFlightDate As Global.System.Web.UI.UserControl

 '''<summary>
 '''lblSummary control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents lblSummary As Global.System.Web.UI.UserControl

 '''<summary>
 '''lblCategory control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents lblCategory As Global.System.Web.UI.UserControl

 '''<summary>
 '''lblFlightType control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents lblFlightType As Global.System.Web.UI.UserControl

 '''<summary>
 '''imgFlightType control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents imgFlightType As Global.System.Web.UI.WebControls.Image

 '''<summary>
 '''lblComments control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents lblComments As Global.System.Web.UI.UserControl

 '''<summary>
 '''lblTotalDistance control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents lblTotalDistance As Global.System.Web.UI.UserControl

 '''<summary>
 '''lblTotalPoints control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents lblTotalPoints As Global.System.Web.UI.UserControl

 '''<summary>
 '''lblLastModified control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents lblLastModified As Global.System.Web.UI.UserControl

 '''<summary>
 '''lblValidated control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents lblValidated As Global.System.Web.UI.UserControl

 '''<summary>
 '''rpPoints control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents rpPoints As Global.System.Web.UI.WebControls.Repeater

 '''<summary>
 '''rpFiles control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents rpFiles As Global.System.Web.UI.WebControls.Repeater

 '''<summary>
 '''rpImages control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents rpImages As Global.System.Web.UI.WebControls.Repeater

 '''<summary>
 '''ctlUploadContainer control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents ctlUploadContainer As Global.System.Web.UI.HtmlControls.HtmlGenericControl

 '''<summary>
 '''lblAddFile control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents lblAddFile As Global.System.Web.UI.UserControl

 '''<summary>
 '''ctlFileUpload control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents ctlFileUpload As Global.System.Web.UI.WebControls.FileUpload

 '''<summary>
 '''cmdUpload control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents cmdUpload As Global.System.Web.UI.WebControls.Button

 '''<summary>
 '''cmdCancel control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents cmdCancel As Global.System.Web.UI.WebControls.LinkButton

 '''<summary>
 '''cmdEdit control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents cmdEdit As Global.System.Web.UI.WebControls.LinkButton

 '''<summary>
 '''cmdDelete control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents cmdDelete As Global.System.Web.UI.WebControls.LinkButton

 '''<summary>
 '''cmdReject control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents cmdReject As Global.System.Web.UI.WebControls.LinkButton

 '''<summary>
 '''cmdValidate control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents cmdValidate As Global.System.Web.UI.WebControls.LinkButton
End Class
